export type TalentPoolCategory = 'general' | 'department' | 'event'

/** Event pools can expose a public application form. */
export type TalentPoolFormStatus = 'live' | 'draft'

export type PoolCandidateStage
  = 'New' | 'Applied' | 'Screened' | 'Interview' | 'Offer' | 'Reference check'

export type PoolFormQuestionType
  = 'Short Text' | 'Long Text' | 'Single Select' | 'Multi Select' | 'Yes / No' | 'Number'

export interface PoolFormQuestion {
  id: string
  label: string
  type: PoolFormQuestionType
  required: boolean
}

/**
 * The public application form an event pool can publish. Full Name and Email are
 * always on it and cannot be removed; phone and résumé are opt-in, and anything
 * else is a custom question.
 */
export interface PoolFormConfig {
  optional: { phone: boolean; resume: boolean }
  questions: PoolFormQuestion[]
}

export interface TalentPool {
  id: string
  name: string
  description: string
  category: TalentPoolCategory
  /** Set when category is 'department'. */
  department?: string
  /** Set when category is 'event'. */
  event?: string
  /**
   * System pools are generated by the product, not by a user — currently only the
   * General Application pool. They cannot be renamed, archived or deleted.
   */
  system?: boolean
  total: number
  /** ISO date, e.g. '2026-04-12'. */
  created: string
  /** TeamMember ids — resolved through useTeam(). */
  members: string[]
  archived: boolean
  /** Pinned pools sort above the rest within their tab. */
  pinned: boolean
  formStatus?: TalentPoolFormStatus
  form?: PoolFormConfig
}

/**
 * A candidate as seen inside a pool. `id` is the real candidate id, so a row
 * links straight to /candidates/{id} — pools and the Candidates module describe
 * the same people, never parallel copies.
 */
export interface PoolCandidate {
  id: string
  poolId: string
  name: string
  initials: string
  avatarColor: string
  stage: PoolCandidateStage
  /** Where they came from — mirrors the candidate's first source. */
  appliedVia: string
  /** Null for spontaneous applicants, who applied without a specific role. */
  jobTitle: string | null
  email: string
  /** 0–100, or null when the candidate has not been scored. */
  aiScore: number | null
  evalScore: number | null
  tags: string[]
  /** ISO date the candidate entered the pool. */
  date: string
}

export interface TalentPoolsResponse {
  pools: TalentPool[]
  candidates: PoolCandidate[]
}
